# OSS-CAEA with native patch-14 encoders and PSAH.
crop_size = (512, 512)
num_classes = 19
model = {'type': 'OSSCAEA',
 'data_preprocessor': {'type': 'SegDataPreProcessor',
                       'mean': [123.675, 116.28, 103.53],
                       'std': [58.395, 57.12, 57.375],
                       'size': (512, 512),
                       'bgr_to_rgb': True,
                       'pad_val': 0,
                       'seg_pad_val': 255},
 'backbone': {'type': 'OSSCAEABackbone',
              'class_json': 'open_vocab/cityscapes.json',
              'vfm_checkpoint': 'checkpoints/dinov2_vitl14_pretrain.pth',
              'depth_checkpoint': 'checkpoints/depth_anything_v2_vitl.pth',
              'clip_checkpoint': 'checkpoints/ViT-L-14.pt',
              'channels': 256,
              'clip_dim': 768,
              'out_indices': (21, 22, 23),
              'image_size': 518,
              'patch_size': 14,
              'embed_dim': 1024,
              'depth': 24,
              'num_heads': 16},
 'decode_head': {'type': 'PSAH',
                 'in_channels': [256, 256, 256, 256],
                 'strides': [4, 8, 16, 32],
                 'feat_channels': 256,
                 'out_channels': 256,
                 'num_classes': 19,
                 'num_queries': 100,
                 'num_transformer_feat_level': 3,
                 'align_corners': False,
                 'pixel_decoder': {'type': 'mmdet.MSDeformAttnPixelDecoder',
                                   'num_outs': 3,
                                   'norm_cfg': {'type': 'GN', 'num_groups': 32},
                                   'act_cfg': {'type': 'ReLU'},
                                   'encoder': {'num_layers': 6,
                                               'layer_cfg': {'self_attn_cfg': {'embed_dims': 256,
                                                                               'num_heads': 8,
                                                                               'num_levels': 3,
                                                                               'num_points': 4,
                                                                               'im2col_step': 64,
                                                                               'dropout': 0.0,
                                                                               'batch_first': True,
                                                                               'norm_cfg': None,
                                                                               'init_cfg': None},
                                                             'ffn_cfg': {'embed_dims': 256,
                                                                         'feedforward_channels': 1024,
                                                                         'num_fcs': 2,
                                                                         'ffn_drop': 0.0,
                                                                         'act_cfg': {'type': 'ReLU',
                                                                                     'inplace': True}}},
                                               'init_cfg': None},
                                   'positional_encoding': {'num_feats': 128, 'normalize': True},
                                   'init_cfg': None},
                 'enforce_decoder_input_project': False,
                 'positional_encoding': {'num_feats': 128, 'normalize': True},
                 'transformer_decoder': {'return_intermediate': True,
                                         'num_layers': 9,
                                         'layer_cfg': {'self_attn_cfg': {'embed_dims': 256,
                                                                         'num_heads': 8,
                                                                         'attn_drop': 0.0,
                                                                         'proj_drop': 0.0,
                                                                         'dropout_layer': None,
                                                                         'batch_first': True},
                                                       'cross_attn_cfg': {'embed_dims': 256,
                                                                          'num_heads': 8,
                                                                          'attn_drop': 0.0,
                                                                          'proj_drop': 0.0,
                                                                          'dropout_layer': None,
                                                                          'batch_first': True},
                                                       'ffn_cfg': {'embed_dims': 256,
                                                                   'feedforward_channels': 2048,
                                                                   'num_fcs': 2,
                                                                   'act_cfg': {'type': 'ReLU',
                                                                               'inplace': True},
                                                                   'ffn_drop': 0.0,
                                                                   'dropout_layer': None,
                                                                   'add_identity': True}},
                                         'init_cfg': None},
                 'loss_cls': {'type': 'mmdet.CrossEntropyLoss',
                              'use_sigmoid': False,
                              'loss_weight': 2.0,
                              'reduction': 'mean',
                              'class_weight': [1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               1.0,
                                               0.1]},
                 'loss_mask': {'type': 'mmdet.CrossEntropyLoss',
                               'use_sigmoid': True,
                               'reduction': 'mean',
                               'loss_weight': 5.0},
                 'loss_dice': {'type': 'mmdet.DiceLoss',
                               'use_sigmoid': True,
                               'activate': True,
                               'reduction': 'mean',
                               'naive_dice': True,
                               'eps': 1.0,
                               'loss_weight': 5.0},
                 'train_cfg': {'num_points': 12544,
                               'oversample_ratio': 3.0,
                               'importance_sample_ratio': 0.75,
                               'assigner': {'type': 'mmdet.HungarianAssigner',
                                            'match_costs': [{'type': 'mmdet.ClassificationCost',
                                                             'weight': 2.0},
                                                            {'type': 'mmdet.CrossEntropyLossCost',
                                                             'weight': 5.0,
                                                             'use_sigmoid': True},
                                                            {'type': 'mmdet.DiceCost',
                                                             'weight': 5.0,
                                                             'pred_act': True,
                                                             'eps': 1.0}]},
                               'sampler': {'type': 'mmdet.MaskPseudoSampler'}},
                 'clip_dim': 768,
                 'alignment_heads': 8,
                 'coarse_loss_weight': 1.0,
                 'coarse_alpha': 0.4},
 'train_cfg': {},
 'test_cfg': {'mode': 'slide', 'crop_size': (512, 512), 'stride': (341, 341)}}
